module.exports = () => [
    {
        id: '13',
        commonId: '83',
        color: 'red',
        type: 'missile',
        name: 'Alien Missile',
        description: 'Slow (each turn can either move or attack but not both)',
        cost: 1,
        attack: 5,
        defense: 1,
        paralyzed: false
    },
        {
        id: '1',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 99,
        defense: 99,
        paralyzed: false
    },
    {
        id: '2',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 99,
        defense: 99,
        paralyzed: false
    },
    {
        id: '3',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 99,
        defense: 99,
        paralyzed: false
    },
    {
        id: '4',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 99,
        defense: 99,
        paralyzed: false
    },
    {
        id: '5',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 99,
        defense: 99,
        paralyzed: false
    },
    {
        id: '6',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 99,
        defense: 99,
        paralyzed: false
    },
    {
        id: '7',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 99,
        defense: 99,
        paralyzed: false
    },
    {
        id: '8',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 99,
        defense: 99,
        paralyzed: false
    },
    {
        id: '9',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 99,
        defense: 99,
        paralyzed: false
    },
    {
        id: '10',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 99,
        defense: 99,
        paralyzed: false
    },
    {
        id: '11',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 99,
        defense: 99,
        paralyzed: false
    },
    {
        id: '12',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 99,
        defense: 99,
        paralyzed: false
    }
];
