module.exports = () => [
    {
        id: '1',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 1,
        defense: 1,
        paralyzed: false
    },
    {
        id: '2',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 1,
        defense: 1,
        paralyzed: false
    },
    {
        id: '3',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 1,
        defense: 1,
        paralyzed: false
    },
    {
        id: '4',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 1,
        defense: 1,
        paralyzed: false
    },
    {
        id: '5',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 1,
        defense: 1,
        paralyzed: false
    },
    {
        id: '6',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 1,
        defense: 1,
        paralyzed: false
    },
    {
        id: '7',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 1,
        defense: 1,
        paralyzed: false
    },
    {
        id: '8',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 1,
        defense: 1,
        paralyzed: false
    },
    {
        id: '9',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 1,
        defense: 1,
        paralyzed: false
    },
    {
        id: '10',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 1,
        defense: 1,
        paralyzed: false
    },
    {
        id: '11',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 1,
        defense: 1,
        paralyzed: false
    },
    {
        id: '12',
        commonId: '6',
        color: 'red',
        type: 'missile',
        name: 'HELLO',
        description: 'I dunno',
        cost: 1,
        attack: 1,
        defense: 1,
        paralyzed: false
    },
    {
        id: '13',
        commonId: '83',
        color: 'red',
        type: 'missile',
        name: 'Alien Missile',
        description: 'Slow (each turn can either move or attack but not both)',
        cost: 1,
        attack: 5,
        defense: 1,
        paralyzed: false
    },
    {
        id: '14',
        commonId: '84',
        color: 'red',
        type: 'missile',
        name: 'Acid Projectile',
        description: 'Fast (can move the first turn). If played from hand: you may draw a card.',
        cost: 1,
        attack: 1,
        defense: 1,
        paralyzed: false
    },
    {
        id: '15',
        commonId: '81',
        color: 'green',
        type: 'defense',
        name: 'Shield',
        description: 'Protects base station. (You can have several Shield in play at the same time.)',
        cost: 1,
        attack: 0,
        defense: 3,
        paralyzed: false
    },
    {
        id: '16',
        commonId: '87',
        color: 'red',
        type: 'duration',
        name: 'Extra Draw',
        description: 'Draw 2 extra cards in your draw phase',
        cost: 2,
        attack: 0,
        defense: 0,
        paralyzed: false
    },
    {
        id: '17',
        commonId: '91',
        color: 'violet',
        type: 'duration',
        name: 'Disturbing Signals',
        description: 'Enemy missiles can\'t move or attack.',
        cost: 1,
        attack: 0,
        defense: 0,
        paralyzed: false
    },
    {
        id: '18',
        commonId: '95',
        color: 'violet',
        type: 'duration',
        name: 'Fast',
        description: 'Your space ships are fast (they can move the first turn they enter play).',
        cost: 1,
        attack: 0,
        defense: 0,
        paralyzed: false
    },
    {
        id: '19',
        commonId: '78',
        color: 'blue',
        type: 'space-ship',
        name: 'Drone',
        description: 'If played from hand: you may draw a card.',
        cost: 1,
        attack: 1,
        defense: 1,
        paralyzed: false
    },
    {
        id: '20',
        commonId: '90',
        color: 'blue',
        type: 'space-ship',
        name: 'Repair',
        description: 'Can repair 3 damage to spaceship or 1 damage to station.',
        cost: 1,
        attack: 0,
        defense: 2,
        paralyzed: false
    },
    {
        id: '21',
        commonId: '86',
        color: 'orange',
        type: 'space-ship',
        name: 'Destroy Duration',
        description: 'After first turn: Sacrifice instead of attacking to destroy a duration card.',
        cost: 1,
        attack: 1,
        defense: 1,
        paralyzed: false
    },
    {

        id: 22,
        commonId: 79,
        color: 'violet',
        type: 'duration',
        name: 'Toxic gas',
        description: 'Deal 1 damage to enemy station at the start of your draw phase. Shields protects but receives 2 damage instead of 1.',
        cost: 1,
        attack: 0,
        defense: 0,
        paralyzed: false
    },
    {

        id: 23,
        commonId: 88,
        color: 'orange',
        type: 'event',
        name: 'Revive',
        description: 'Deal 1 damage to enemy station at the start of your draw phase. Shields protects but receives 2 damage instead of 1.',
        cost: 3,
        attack: 0,
        defense: 0,
        paralyzed: false
    }
];
