const DONE = [
    {
        "id": "21",
        "name": "Energy Shield",
        "price": "3",
        "type_card": "green",
        "detail": "Protects base station. (You can only have one Energy Shield in play at the same time.)",
        "defense": "5",
        "attack": "0",
        "number_copies": "3",
    },
    {
        group: 'Can attack 2 times per turn',
        items: [{
            "id": "23",
            "name": "Small Cannon",
            "price": "1",
            "type_card": "green",
            "detail": "Can attack 2 times per turn.",
            "defense": "1",
            "attack": "2",
            "number_copies": "0",
        },
            {
                "id": "24",
                "name": "Trigger-Happy Joe",
                "price": "2",
                "type_card": "blue",
                "detail": "Can attack 2 times per turn.",
                "defense": "2",
                "attack": "1",
                "number_copies": "1",
            },
        ]
    },
    {
        "id": "6",
        "name": "Fast Missile",
        "price": "2",
        "type_card": "red",
        "detail": "Can move the first turn.",
        "defense": "1",
        "attack": "2",
        "number_copies": "1",
    },
    {
        "id": "28",
        "name": "Hunter",
        "price": "3",
        "type_card": "blue",
        "detail": "Can move the first turn.",
        "defense": "1",
        "attack": "2",
        "number_copies": "2",
    },
    {
        "id": "29",
        "name": "New Hope",
        "price": "2",
        "type_card": "blue",
        "detail": "Can repair 3 damage instead of attacking. Can move the first turn.",
        "defense": "3",
        "attack": "1",
        "number_copies": "1",
    },
];

const COUNTERS = [
    {
        "id": "16",
        "name": "Target Missed",
        "price": "0",
        "type_card": "orange",
        "detail": "Play this card directly during enemy attack from space ship (not colisision, missile or cannon) to make it fail. [ OR ] Draw 1 card.",
        "defense": "0",
        "attack": "0",
        "number_copies": "3",
    },
    {
        "id": "31",
        "name": "Luck",
        "price": "0",
        "type_card": "orange",
        "detail": "Counter target card costing 2 or less.\r\n[ OR ] Draw 2 cards.",
        "defense": "0",
        "attack": "0",
        "number_copies": "4",
    },
    {
        "id": "34",
        "name": "Avoid",
        "price": "2",
        "type_card": "violet",
        "detail": "Discard this card from table to counter card being played.",
        "defense": "0",
        "attack": "0",
        "number_copies": "2",
    },

];

const HEAVY_GUI = [
    {
        "id": "8",
        "name": "Kamikaze Nuke",
        "price": "2",
        "type_card": "red",
        "detail": "Carried by ship with defense 3 or more. Replaces defense to 3. Ship that carries dies in attack (collision).",
        "defense": "3",
        "attack": "10",
        "number_copies": "1",
    },
    {
        "id": "13",
        "name": "Over Capacity",
        "price": "2",
        "type_card": "violet",
        "detail": "You have no maximum hand size.\r\nDuring your action phase you may look at and move station cards to your hand.",
        "defense": "0",
        "attack": "0",
        "number_copies": "2",
    },
    {
        "id": "15",
        "name": "Supernova",
        "price": "10",
        "type_card": "orange",
        "detail": "All cards except station cards are destroyed. Each player receives 3 station damage and discards 3 cards. Your turn is ended.",
        "defense": "0",
        "attack": "0",
        "number_copies": "1",
    },
    {
        "id": "17",
        "name": "Missiles Launched",
        "price": "5",
        "type_card": "orange",
        "detail": "Find 2 missile cards (red cards) from your draw or discard pile and play them without cost.",
        "defense": "0",
        "attack": "0",
        "number_copies": "1",
    },
    {
        "id": "18",
        "name": "Perfect Plan",
        "price": "2",
        "type_card": "orange",
        "detail": "Search for a card from the draw pile, discard pile or station cards and put it into your hand.",
        "defense": "0",
        "attack": "0",
        "number_copies": "1",
    },
    {
        "id": "27",
        "name": "The Shade",
        "price": "4",
        "type_card": "blue",
        "detail": "Stealth (invisible upside down, becomes visible when attacking).\r\nCan enter stealth instead of attacking.",
        "defense": "4",
        "attack": "3",
        "number_copies": "1",
    },
];

const EASY_GUI = [
    {
        "id": "2",
        "name": "The Dark Destroyer",
        "price": "6",
        "type_card": "blue",
        "detail": "Opponent may draw 2 cards when this enters play.",
        "defense": "10",
        "attack": "7",
        "number_copies": "1",
    },
    {
        "id": "7",
        "name": "EMP Missile",
        "price": "2",
        "type_card": "red",
        "detail": "Destroys Energy Shield or paralyzes space ship (turn the card and it cannot do anything until repaired).",
        "defense": "2",
        "attack": "0",
        "number_copies": "2",
    },
    {
        "id": "14",
        "name": "Excellent work",
        "price": "2",
        "type_card": "orange",
        "detail": "Put down this card as an extra station card.\r\n[ OR ] Draw 3 cards.",
        "defense": "0",
        "attack": "0",
        "number_copies": "3",
    },
    {
        "id": "19",
        "name": "Pursuiter",
        "price": "1",
        "type_card": "blue",
        "detail": "You may sacrifice Pursuiter from play instead of attacking to deal 4 damage to target in same zone (collision).",
        "defense": "1",
        "attack": "2",
        "number_copies": "2",
    },
    {
        "id": "20",
        "name": "Grand Oppurtunity",
        "price": "5",
        "type_card": "orange",
        "detail": "Draw 6 cards and then discard 2 cards from your hand.",
        "defense": "0",
        "attack": "0",
        "number_copies": "1",
    },
    {
        "id": "38",
        "name": "Fatal Error",
        "price": "0",
        "type_card": "orange",
        "detail": "Destroy any card in play (on the table including station cards).\r\nThe opponent may draw 2 cards.",
        "defense": "0",
        "attack": "0",
        "number_copies": "2",
    },
    {
        "id": "40",
        "name": "Expansion",
        "price": "1",
        "type_card": "violet",
        "detail": "You may put down or move an extra station card each turn, if you do the opponent may draw a card.",
        "defense": "0",
        "attack": "0",
        "number_copies": "2",
    },
    {
        "id": "42",
        "name": "Discovery",
        "price": "0",
        "type_card": "orange",
        "detail": "Each player draws 4 cards.\r\n[ OR ] Each player discards 2 cards.",
        "defense": "0",
        "attack": "0",
        "number_copies": "2",
    },
    {
        "id": "57",
        "name": "* Station *",
        "price": "0",
        "type_card": "orange",
        "detail": "Draw 1 card. (normally used as a station card)",
        "defense": "0",
        "attack": "0",
        "number_copies": "0"
    }
];

const NO_GUI = [
    {
        "id": "9",
        "name": "Full Force Forward",
        "price": "3",
        "type_card": "violet",
        "detail": "\u00b7 +1 attack of your space ships (blue).\r\n\u00b7 Your space ships can move the first turn     they enter play.",
        "defense": "0",
        "attack": "0",
        "number_copies": "2",
    },
    {
        "id": "10",
        "name": "Defense Focus",
        "price": "3",
        "type_card": "violet",
        "detail": "Prevent the first damage in attacks to your space ships.",
        "defense": "0",
        "attack": "0",
        "number_copies": "0",
    },
    {
        "id": "11",
        "name": "Good Karma",
        "price": "3",
        "type_card": "violet",
        "detail": "Draw 4 extra cards in your draw phase, then after your draw phase discard 2 cards from your hand.",
        "defense": "0",
        "attack": "0",
        "number_copies": "2",
    },
    {
        "id": "12",
        "name": "Neutralization",
        "price": "2",
        "type_card": "violet",
        "detail": "No other duration card has any effect.",
        "defense": "0",
        "attack": "0",
        "number_copies": "2",
    },
    {
        "id": "30",
        "name": "The Last Hope",
        "price": "3",
        "type_card": "blue",
        "detail": "Can repair 5 damage instead of attacking.",
        "defense": "5",
        "attack": "1",
        "number_copies": "1",
    },
    {
        "id": "33",
        "name": "Confusing Orders",
        "price": "1",
        "type_card": "orange",
        "detail": "Target enemy space ship cannot do anything next turn.",
        "defense": "0",
        "attack": "0",
        "number_copies": "0",
    },
    {
        "id": "37",
        "name": "Disturbing Sensor",
        "price": "4",
        "type_card": "blue",
        "detail": "\u00b7 Enemy missiles can't move or attack.\r\n\u00b7 If opponent after draw phase has more   than 1 card in hand, he or she           discards a card.",
        "defense": "4",
        "attack": "0",
        "number_copies": "1",
    },
    {
        "id": "39",
        "name": "Deadly Sniper",
        "price": "4",
        "type_card": "blue",
        "detail": "Long distance shooter.\r\n(Can after the first turn shoot targets in enemy zone from home zone)",
        "defense": "4",
        "attack": "2",
        "number_copies": "1",
        "image_card": "https:\/\/admin.thespacewar.com\/source\/services\/generate_card_md_39.png"
    },
];

const AVG_WEEKLY_WORK_TIME = 15;
const WEEKS_UNTIL_RELEASE = 8;
const categories = [
    { name: 'Counters', tasks: COUNTERS, leadTime: 4 },
    { name: 'Heavy GUI', tasks: HEAVY_GUI, leadTime: 6 },
    { name: 'Easy GUI', tasks: EASY_GUI, leadTime: 3 },
    { name: 'No GUI', tasks: NO_GUI, leadTime: 2 }
];
const printCategory = (name, tasks, leadTime) => console.log(`${name}: ${tasks.length}  \tEst. ${leadTime * tasks.length}h`);

console.log('DONE: ' + DONE.length);
categories.forEach(category => printCategory(category.name, category.tasks, category.leadTime));
const totalEstimate = categories.reduce((acc, c) => acc + c.leadTime * c.tasks.length, 0);
console.log('Total estimate: ' + totalEstimate + 'h (' + (totalEstimate / 24) + ' days)');
console.log('Done in ' + totalEstimate / AVG_WEEKLY_WORK_TIME + ' weeks');
console.log('You will... ' + (totalEstimate / AVG_WEEKLY_WORK_TIME < WEEKS_UNTIL_RELEASE ? 'SUCCEED :)' : 'FAIL :('));